package synthhist

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"math"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/tsdb"
	"gopkg.in/yaml.v3"
)

// Metric names the generator emits — counter semantics, cumulative like a
// real scrape target, so rate()/increase() behave normally in replay.
const (
	MetricRequests = "synthetic_requests_total"
	MetricErrors   = "synthetic_errors_total"
)

// Generate fabricates the history: TSDB blocks under dir/blocks and a
// matching incident registry at dir/incidents.yaml. Deterministic for a
// given spec (seeded RNG) so tests and demos are reproducible.
func Generate(ctx context.Context, spec Spec, dir string) error {
	blocksDir := filepath.Join(dir, "blocks")
	if err := os.MkdirAll(blocksDir, 0o755); err != nil {
		return err
	}

	discard := slog.New(slog.NewTextHandler(io.Discard, nil))
	w, err := tsdb.NewBlockWriter(discard, blocksDir, tsdb.DefaultBlockDuration)
	if err != nil {
		return fmt.Errorf("block writer: %w", err)
	}
	defer func() { _ = w.Close() }()

	rng := rand.New(rand.NewSource(spec.Seed))
	app := w.Appender(ctx)

	// cumulative counters per (service, metric)
	reqTotal := map[string]float64{}
	errTotal := map[string]float64{}

	samples := 0
	for t := spec.From; t.Before(spec.To); t = t.Add(spec.Step) {
		for _, svc := range spec.Services {
			ratio := svc.ErrorRatio
			for _, inc := range spec.Incidents {
				if inc.Service == svc.Name && !t.Before(inc.Start) && t.Before(inc.End) {
					ratio = inc.ErrorRatio
				}
			}
			jitter := 1.0
			if svc.Jitter > 0 {
				jitter = 1 + (rng.Float64()*2-1)*svc.Jitter
			}
			reqs := svc.RatePerSec * spec.Step.Seconds() * jitter
			errs := reqs * ratio
			reqTotal[svc.Name] += reqs
			errTotal[svc.Name] += errs

			ms := t.UnixMilli()
			if _, err := app.Append(0, labels.FromStrings("__name__", MetricRequests, "service", svc.Name), ms, math.Round(reqTotal[svc.Name])); err != nil {
				return err
			}
			if _, err := app.Append(0, labels.FromStrings("__name__", MetricErrors, "service", svc.Name), ms, math.Round(errTotal[svc.Name])); err != nil {
				return err
			}
			samples += 2
		}
		// flush per day of samples to bound memory
		if samples > 500_000 {
			if err := app.Commit(); err != nil {
				return err
			}
			if _, err := w.Flush(ctx); err != nil {
				return fmt.Errorf("flushing blocks: %w", err)
			}
			app = w.Appender(ctx)
			samples = 0
		}
	}
	if err := app.Commit(); err != nil {
		return err
	}
	if _, err := w.Flush(ctx); err != nil {
		return fmt.Errorf("flushing blocks: %w", err)
	}

	return writeRegistry(spec, filepath.Join(dir, "incidents.yaml"))
}

// writeRegistry emits the ground truth matching the embedded signatures, in
// the incidents.yaml v1 schema the backtest scores against.
func writeRegistry(spec Spec, path string) error {
	type inc struct {
		ID       string   `yaml:"id"`
		Title    string   `yaml:"title"`
		Start    string   `yaml:"start"`
		End      string   `yaml:"end"`
		Services []string `yaml:"services"`
		Induced  bool     `yaml:"induced"`
		Notes    string   `yaml:"notes"`
	}
	reg := struct {
		Version   int   `yaml:"version"`
		Incidents []inc `yaml:"incidents"`
	}{Version: 1}

	sorted := append([]SynthIncident(nil), spec.Incidents...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Start.Before(sorted[j].Start) })
	for _, i := range sorted {
		reg.Incidents = append(reg.Incidents, inc{
			ID:       i.ID,
			Title:    fmt.Sprintf("synthetic: %s error ratio %.0f%% on %s", i.Service, i.ErrorRatio*100, i.Service),
			Start:    i.Start.UTC().Format(time.RFC3339),
			End:      i.End.UTC().Format(time.RFC3339),
			Services: []string{i.Service},
			Induced:  true,
			Notes:    "generated by argus devtools synth-history — ground truth for the embedded signature",
		})
	}
	b, err := yaml.Marshal(reg)
	if err != nil {
		return err
	}
	header := "# GENERATED by argus devtools synth-history — matches the embedded incident signatures.\n"
	return os.WriteFile(path, append([]byte(header), b...), 0o644)
}
